[build]
  command = "npm run build:client"
  publish = "dist/spa"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API calls to your Render server
[[redirects]]
  from = "/api/*"
  to = "https://your-render-app-name.onrender.com/api/:splat"
  status = 200
  force = true
